= Couchbase Component
:doctitle: Couchbase
:shortname: couchbase
:artifactid: camel-couchbase
:description: Query Couchbase databases using SQL (N1QL) queries or MapReduce Views with a poll strategy and/or perform various operations against Couchbase databases.
:since: 2.19
:supportlevel: Stable
:tabs-sync-option:
:component-header: Both producer and consumer are supported
//Manually maintained attributes
:camel-spring-boot-name: couchbase

*Since Camel {since}*

*{component-header}*

The *couchbase:* component allows you to treat
https://www.couchbase.com/[Couchbase] instances as a producer or consumer
of messages.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
------------------------------------------------------------
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-couchbase</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
------------------------------------------------------------

== URI format

-------------------------------------------------
couchbase:url
-------------------------------------------------


// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
include::partial$component-endpoint-headers.adoc[]
// component options: END

== Consuming documents

The consumer supports two query modes for polling documents from Couchbase:

=== SQL++ queries (recommended)

Since Couchbase Server 7.0, the recommended way to query documents is using SQL++ (formerly N1QL).
MapReduce Views are deprecated since Couchbase 7.0 and do not work with the Magma storage backend
(default since Couchbase 8.0).

To use SQL++ queries, set the `statement` endpoint option:

[source,java]
----
from("couchbase:http://localhost?bucket=myBucket&username=user&password=pass"
    + "&statement=SELECT META().id AS __id, * FROM `myCollection` LIMIT 100")
    .to("direct:result");
----

The query must include `META().id AS \__id` in the SELECT clause so the consumer can identify each document.
When `fullDocument` is `true` (the default), the consumer fetches the complete document from the KV store using
the document ID. When `false`, the query result row is used directly as the message body.

NOTE: SQL++ queries require a primary index or appropriate secondary index on the bucket/collection.
Create one with: `CREATE PRIMARY INDEX ON \`myBucket\`` or via the Couchbase SDK.

=== MapReduce Views (deprecated)

The consumer can also poll documents using MapReduce Views via the `designDocumentName` and `viewName`
endpoint options. This mode is deprecated and will be removed in a future release.

[source,java]
----
from("couchbase:http://localhost?bucket=myBucket&username=user&password=pass"
    + "&designDocumentName=myDoc&viewName=myView&limit=10")
    .to("direct:result");
----

=== Migrating from Views to SQL++

The following table shows how to migrate from MapReduce View options to equivalent SQL++ queries:

[cols="1,1,2",options="header"]
|===
| View option | SQL++ equivalent | Example

| `designDocumentName` + `viewName`
| `statement`
| The view's map function determines what is emitted. Write an equivalent SQL++ query with a `WHERE` clause.

| `limit=10`
| `LIMIT 10` in the query
| `SELECT META().id AS \__id, * FROM \`bucket\` LIMIT 10`

| `skip=5`
| `OFFSET 5` in the query
| `SELECT META().id AS \__id, * FROM \`bucket\` LIMIT 10 OFFSET 5`

| `descending=true`
| `ORDER BY ... DESC` in the query
| `SELECT META().id AS \__id, * FROM \`bucket\` ORDER BY META().id DESC`

| `rangeStartKey` / `rangeEndKey`
| `WHERE` clause in the query
| `SELECT META().id AS \__id, * FROM \`bucket\` WHERE META().id >= 'start' AND META().id \<= 'end'`

| `fullDocument=true`
| Works the same way
| When `true`, the consumer fetches the full document via KV get regardless of query mode.
|===

For example, a view-based consumer like:

[source,java]
----
from("couchbase:http://localhost?bucket=myBucket&username=user&password=pass"
    + "&designDocumentName=myDoc&viewName=myView&limit=10&descending=true")
----

Can be migrated to:

[source,java]
----
from("couchbase:http://localhost?bucket=myBucket&username=user&password=pass"
    + "&statement=SELECT META().id AS __id, * FROM `myBucket` ORDER BY META().id DESC LIMIT 10")
----

== Couchbase SDK compatibility

Using collections and scopes is supported only for Couchbase Server 7.0 and later.

This component is currently using Java SDK 3.x, so it might be not compatible with older Couchbase servers anymore.
Check the compatibility https://docs.couchbase.com/java-sdk/current/project-docs/compatibility.html[page] for details.

 * The value formerly interpreted as a bucket-name is now interpreted as a username. The username must correspond to a user defined on the cluster that is being accessed.
 * The value formerly interpreted as a bucket-password is now interpreted as the password of the defined user.


include::spring-boot:partial$starter.adoc[]
